import { Geist, Geist_Mono } from 'next/font/google';
import { Header } from '@/layouts/Header';
import { Footer } from '@/layouts/Footer';
import PrelineScript from '@/components/PrelineScript';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Tesla Web App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`flex flex-col antialiased finlandica-custom`}>
        <Header />
        {children}
        <PrelineScript />
        <Footer />
      </body>
    </html>
  );
}
